### ISSUE TITLE
vue3+vite isFunction is not a function

### ISSUE THREAD

**Issue by KinedYK** [HJ29/vue3-scroll-picker#8]
runtime-core.esm-bundler.js:2244 Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2244:12)
    at LocaleReceiver.js:4:16

**Comment by bryne-k** [comment]
所以，朋友你的这个问题如何解决的哇

**Comment by bryne-k** [comment]
这个问题是采用的vue版本导致的，从vue/shared导出的部分公用函数为undefined，锁一个vue版本即可

**Comment by smallsun-lgtm** [comment]
> 这个问题是采用的vue版本导致的，从vue/shared导出的部分公用函数为undefined，锁一个vue版本即可

但是并没有解决会出现isFunction is not a  function的问题，难道是因为还是版本高，但是前两天还是正常的
